[tool.bandit]
recursive = true

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
files = "pycep"
strict = true
implicit_reexport = true

[[tool.mypy.overrides]]
module = [
    "assertpy"
]
ignore_missing_imports = true
